### ISSUE TITLE
`node: not found` error in BB Pipelines

### ISSUE THREAD

**Issue by Toreno96** [apptension/aws-boilerplate#53]
# Steps to reproduce

1. Run **Bitbucket Pipeline** `test async workers`.

# Encountered behavior

There is unhandled `node: not found` error during steps `install-test` and `test-bb-ci`. The steps continues and finishes successfully.

```shell
+ make -C services/workers install-test PROJECT_NAME=test ENV_STAGE=test
make: Entering directory '/opt/atlassian/pipelines/agent/build/services/workers'
pipenv install --dev
/bin/sh: 1: node: not found
Creating a virtualenv for this project…
Pipfile: /opt/atlassian/pipelines/agent/build/services/workers/Pipfile
Using /usr/local/bin/python3.8 (3.8.5) to create virtualenv…
```

```shell
+ make -C services/workers test-bb-ci PROJECT_NAME=test ENV_STAGE=test
make: Entering directory '/opt/atlassian/pipelines/agent/build/services/workers'
bash ./scripts/run_tests.sh
/bin/sh: 1: node: not found
All done! ✨ 🍰 ✨
26 files would be left unchanged.
wait-for-it.sh: waiting 15 seconds for localhost:5432
wait-for-it.sh: localhost:5432 is available after 0 seconds
running test
```

**There is no such behavior in GitHub Actions defined for the project.**

# Expected behavior

Both steps (and the whole Pipeline in general) runs without any, especially unhandled, errors.

Unhandled errors that does not have actual influence on run of the Pipeline, unnecessary confuses the users.

# Cause of the issue

Bitbucket Pipeline for `test async workers` uses image `python:3.8`, which does not have Node.js installed by default, while running the tests directly in this image:

```shell
$ docker run -it python:3.8 bash
root@420d6268cc7b:/# node
bash: node: command not found
```

**GitHub Actions uses ubuntu-latest with all the dependencies pre-configured.**

Also, the place where node is used is _probably_ the `base.mk`:

```make
define GetFromCfg
$(shell node -p "require('$(CONFIG_FILE)').$(1)")
endef
```

That would explain why the error does not influence the run of the Pipeline.

# Possible solutions

## Use image with all the dependencies installed

Similar to GitHub Actions.

For example, the python:3.8 with node.js installed, e.g. https://hub.docker.com/r/dstasczak/pythonwithnodejs.

## Run tests of worker in docker

Similar to `test backend`.

It would probably require a lot of work (definition of docker-compose, Dockerfile, and adjustments in Makefile).

However, it could allow to also make this step more consistent between GH Actions, BB Pipelines and local environment.

## Remove the reason of error

If `node` is not actually required during the `test async workers` then there should not be any error if it is not installed there.

**Comment by pziemkowski** [comment]
Resolved in #55
